#!/bin/bash

# Get the C file name from the environment variable
CFILE=$CFILE

# Define the output file name
OUTPUT_FILE=c

# Run the preprocessor and save the output to the output file
cpp $CFILE > $OUTPUT_FILE